### ISSUE TITLE
what is the function of this variable?

### ISSUE THREAD

**Issue by gendumaster** [andikscript/react-native-custom#4]
https://github.com/andikscript/react-native-custom/blob/a73a15776a18e8b3aeb44d7808c3d4f9618dcea9/components/HeaderImageFolding/HeaderImageFolding.js#L10

**Comment by andikscript** [comment]
this variable is used to reference the value of the animation to be executed. so when the application is running and the animation is running, the variable's value always changes according to the behavior of the animation

**Comment by gendumaster** [comment]
thank you
