### ISSUE TITLE
why is there a fork here?

### ISSUE THREAD

**Issue by gendumaster** [andikscript/react-native-custom#5]
https://github.com/andikscript/react-native-custom/blob/a73a15776a18e8b3aeb44d7808c3d4f9618dcea9/components/HeaderFolding/HeaderFolding.js#L65

**Comment by andikscript** [comment]
used to set the status bar when the folding header has arrived at the border of the status bar header so that the color changes

**Comment by gendumaster** [comment]
ok thank for your answer
